spring:
  profiles:
    active: dev

---
server:
  port: 8201

spring:
  profiles: dev
  application:
    name: springcloud2-config-dev
eureka:
    client:
      service-url:
        defaultZone: http://localhost1:8001/eureka/

---

server:
  port: 8202

spring:
  profiles: test
  application:
    name: springcloud2-config-test
eureka:
    client:
      service-url:
        defaultZone: http://localhost1:8001/eureka/